config/routes.rb
KidsGames::Application.routes.draw do
  resources :stories
  match 'hangman' => 'hangman#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :story
  attr_accessible :body, :number
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :pages

  attr_accessible :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hang_men_controller.rb
class HangMenController < ApplicationController
  # GET /hang_men
  # GET /hang_men.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hang_men }
    end
  end
end

app/controllers/hangman_controller.rb
class HangmanController < ApplicationController
  # GET /hang_men
  # GET /hang_men.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hang_men }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hang_men_helper.rb
module HangMenHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/hangman/index.html.haml
%link(rel="import" href="../bower_components/polymer/polymer.html")
%link(rel="import" href="elements/kg-hangman.html")
%kg-hangman

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KidsGames
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/stories/_form.html.haml
= form_for(@story) do |f|
  - if @story.errors.any?
    #error_explanation
      %h2
        = pluralize(@story.errors.count, "error")
        prohibited this story from being saved:
      %ul
        - @story.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/stories/edit.html.haml
%h1 Editing story
= render 'form'
= link_to 'Show', @story
|
\#{link_to 'Back', stories_path}

app/views/stories/index.html.haml
%h1 Listing stories
%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th
  - @stories.each do |story|
    %tr
      %td= story.title
      %td= story.body
      %td= link_to 'Show', story
      %td= link_to 'Edit', edit_story_path(story)
      %td= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Story', new_story_path

app/views/stories/new.html.haml
%h1 New story
= render 'form'
= link_to 'Back', stories_path

app/views/stories/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @story.title
%p
  %b Body:
  = @story.body
= link_to 'Edit', edit_story_path(@story)
|
\#{link_to 'Back', stories_path}